### ISSUE TITLE
Restore from BACPAC

### ISSUE THREAD

**Issue by GraemeSMiller** [AMVSoftware/Cake.SqlServer#17]
I see you added the feature to restore database from SQL backup with _RestoreSqlBackup_. That is really good but I do most of my stuff from _BACPAC_. Be great if we could have similar from _BACPAC_.

**Comment by trailmax** [comment]
Exporting and restoring bacpac are very simple - it is not even funny: https://github.com/AMVSoftware/Cake.SqlServer/blob/backpac/src/Cake.SqlServer/SqlBacpacImpl.cs

I'm not sure this should be a part of this project - adds a 2-line wrappers for a MS library by nuget: https://www.nuget.org/packages/Microsoft.SqlServer.DacFx.x64

**Comment by GraemeSMiller** [comment]
Good work. Yeah 2 lines for Nuget seems excessive! Although NPM is full of stuff like that.

Aren't a lot of dependencies and at least you will know if MS change anything.

Look forward to using it.

**Comment by trailmax** [comment]
This is now implemented as part of the package in v1.6.0
