### ISSUE TITLE
GPLv3 is too restrictive for Plugin Usage

### ISSUE THREAD

**Issue by DustinVenegas** [AMVSoftware/Cake.SqlServer#20]
This project is licensed under the GPLv3 license. 

While this license can be favorable to many open source projects, the full extent of linking libraries with proprietary programs haven't been legally resolved. 

The GPL clearly states all derivative works must also by under the GPL. I would rather not release my personal works under the GPL. I am unable to release some works under the GPL at all. Linking to this library in a CAKE Build script puts that project in jeopardy with this license.

Please consider a different license.

**Comment by trailmax** [comment]
What licence do you suggest? I have not thought about a type of licence for longer than a second, so not bothered about it at all.

**Comment by trailmax** [comment]
Updated licence to MIT - same as the main Cake repository
