### ISSUE TITLE
Need to be able to execute queries

### ISSUE THREAD

**Issue by trailmax** [AMVSoftware/Cake.SqlServer#26]
Need to be able to execute SQL queries and return results in C# objects
Probably expose PetaPoco database object, but compile it as part of the Cake.SqlServer.dll

**Comment by jnm2** [comment]
Does PetaPoco support materializing immutable structs and classes by passing everything via constructor?

**Comment by trailmax** [comment]
@jnm2  do you mean classes like this?

```c#
public class MyProduct
{
    public String Name { get; private set; }
    public String Description { get; private set; }

    public MyProduct(string name, string descr)
    {
            Name = name;
            Description = descr;
    }
}
```
No, I don't think so PetaPoco will handle this. What I've seen/used before were POCOs, same as for EF:

```c#
public class MyProduct
{
    public String Name { get; set; }
    public String Description { get; set; }
}
```

**Comment by jnm2** [comment]
Yes. BTW they are both POCOs because neither inherits from a persistence base class or has a state tracking property.

**Comment by trailmax** [comment]
After looking and thinking about this for a while I came to conclusion that querying should not be part of this project. If you need to query just use `Dapper` or `PetaPoco` via NuGets available. These do querying far better than I'll ever produce here.
