### ISSUE TITLE
Add XML Documentation File

### ISSUE THREAD

**Issue by gep13** [AMVSoftware/Cake.SqlServer#3]
So that the Cake Website Documentation can be generated.

You will see an example of where that get included in the NuSpec file here:

https://github.com/cake-contrib/Cake.VsCode/blob/develop/nuspec/nuget/Cake.VsCode.nuspec#L19

And this is where you can generate that file in the Project properties:

![image](https://cloud.githubusercontent.com/assets/1271146/18413263/ba3c1342-779a-11e6-8b4c-2a5c555fc9ff.png)

**Comment by trailmax** [comment]
Fixed: https://github.com/AMVSoftware/Cake.SqlServer/blob/master/src/Cake.SqlServer/Cake.SqlServer.nuspec#L23
