### ISSUE TITLE
Sql Timeout on Restore despite SetSqlCommandTimeout

### ISSUE THREAD

**Issue by josdeweger** [AMVSoftware/Cake.SqlServer#30]
First of all: awesome work on this Addin!

Restoring a 33gb .bak file returns the following error:

> Error: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

Restoring it via Sql Management Studio works fine. 

Here's the relevant code from the Cake file:

```
SetSqlCommandTimeout(9999); //9999 seconds

foreach(var db in Config.DatabaseDetails.Databases)
{
    var backupFilePath = new FilePath(db.DbBackupFile);
    backupFilePath = backupFilePath.MakeAbsolute(Context.Environment);
    Information("Backup File Path: " + backupFilePath);
            
    RestoreSqlBackup(Config.DatabaseDetails.SqlConnectionString, backupFilePath, 
        new RestoreSqlBackupSettings() 
        {
            NewDatabaseName = db.DbName,
            WithReplace = true
        });
}
```

Any idea why the Command Timeout is not working?

**Comment by trailmax** [comment]
Whoa! 33Gb is a lot!
I suspect you are hitting limitation of `System.Data.SqlClient` that is actually driving this addin. And SSMS does not use this library. How long does it take in SSMS? 9999 seconds is about 2.77 hous - that does not sound a lot of time for 33Gb.

**Comment by josdeweger** [comment]
Thanks for the quick reply!

It's big indeed, I'd rather use a (very) small db, but that's not really an option for me atm. In SSMS it takes about 60 seconds to restore. 

Restoring a 550mb db via the addin works fine btw.

**Comment by trailmax** [comment]
60sec for 33Gb sounds very quick. I don't think I can copy that much data from one SSD to another, let alone dealing with DB restoring. 

I'd try restoring this DB via SQL command (you can get one from the execution of logs in cake) and try run it in SSMS. And see how much time it takes.

**Comment by josdeweger** [comment]
```
RESTORE DATABASE MyDb 
   FROM DISK = 'MyPath\To\Db.bak'; 
```

Results:
Processed 4168456 pages for database 'MyDb', file 'MyDb ' on file 1.
Processed 5 pages for database 'MyDb ', file 'MyDb_log' on file 1.
RESTORE DATABASE successfully processed 4168461 pages in 46.260 seconds (703.979 MB/sec).

Might there be another timeout limit being hit than the SqlCommandTimout?

**Comment by trailmax** [comment]
If you run this command through `ExecuteSqlCommand` method, do you get the same result? Because `RestoreSqlBackup` does a slightly different stuff: https://github.com/AMVSoftware/Cake.SqlServer/blob/master/src/Cake.SqlServer/Backup/SqlBackupsImpl.cs#L25-L31 
First we set the DB into the single user mode and that might take forever (or even be locked if the DB is in heavy use). 
And after the restore we set the DB back into multi-user mode: https://github.com/AMVSoftware/Cake.SqlServer/blob/master/src/Cake.SqlServer/Backup/SqlBackupsImpl.cs#L47

So for your case you might be better off doing your restore via plain sql, without resorting to `RestoreSqlBackup`

**Comment by josdeweger** [comment]
Alright, thanks! This does the trick for me:

```
SetSqlCommandTimeout(300); //5 minutes

var backupFilePath = new FilePath(db.DbBackupFile);
backupFilePath = backupFilePath.MakeAbsolute(Context.Environment);
Information("Backup File Path: " + backupFilePath);

var restoreSqlCommand = "RESTORE DATABASE " + db.DbName + " FROM DISK = '" + backupFilePath + "' WITH REPLACE;";
            
ExecuteSqlCommand(Config.DatabaseDetails.SqlConnectionString, restoreSqlCommand);
```

**Comment by trailmax** [comment]
Awesome! 
There probably should be an option to set or not set the db into a single-user mode. Not everyone would want it.

**Comment by jnm2** [comment]
Huh, I wonder if this explains why the timeout of 5 minutes is exceeded with restoring a .`bak` on LocalDB on our build server every time if we haven't run a build for a while.

**Comment by trailmax** [comment]
@jnm2 yeah, I wonder if switching the db into single user mode was a good idea at all

**Comment by jnm2** [comment]
It's what SSMS does every time, and I did run into scenarios multiple times where restore was actually hanging because I didn't enter single-user mode. It's basically a way to kick all the connections. I believe it corresponds to the "Close existing connections" checkbox in SSMS.

**Comment by jnm2** [comment]
Which means it's weird that sometimes it's the cause of a hang, because it's there to prevent hangs.

**Comment by trailmax** [comment]
@jnm2 I've seen attempts to change the DB into a single user mode causing a lock when the DB was under heavy use with long-running transactions open. But that 's strange for you to get this lock if you are working with LocalDB (assuming no other usage on that DB)

**Comment by trailmax** [comment]
@josdeweger FYI new version (1.8.0) of this addon has an option to disable going into a single user mode for backup restoring: https://github.com/AMVSoftware/Cake.SqlServer/blob/b91eb17744268841ee0995a62374a99a7e2d6984/src/Cake.SqlServer/Backup/RestoreSqlBackupSettings.cs#L16

**Comment by josdeweger** [comment]
Nice! As soon as I have the chance I will give it a try

**Comment by Roemer** [comment]
Keep in mind that you still need to increase the timeout with `SetSqlCommandTimeout` !
