### ISSUE TITLE
LocalDB execution should automatically detect available version

### ISSUE THREAD

**Issue by trailmax** [AMVSoftware/Cake.SqlServer#32]
I keep needing to update what LocalDB version I would like to use - just pick an available version so it works everywhere.

**Comment by trailmax** [comment]
Just don't provide version parameter, you dummy, it'll be handled for you @trailmax

**Comment by jnm2** [comment]
Careful there, be nice to @trailmax 😆

**Comment by trailmax** [comment]
@jnm2  🤣
