### ISSUE TITLE
The assembly 'Cake.SqlServer...' is referencing an older version of Cake.Core (0.20.0).

### ISSUE THREAD

**Issue by daliborpernica** [AMVSoftware/Cake.SqlServer#34]
Please do update Cake.Core to version 0.22 to avoid following error message:

`Error: The assembly 'Cake.SqlServer, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.20.0). 
This assembly need to reference at least Cake.Core version 0.22.0. 
Another option is to downgrade Cake to an earlier version. 
It's not recommended, but you can explicitly opt-out of assembly verification 
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true", 
envrionment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
Process exited with code 1`

Thank you!

**Comment by kmc059000** [comment]
I am also receiving this. Not that it is this project's fault, but this is concerning since it is blocking my deployment process and preventing me from deploying.

**Comment by kmc059000** [comment]
See here: https://www.cakebuild.net/blog/2017/09/cake-v0.22.0-released

**Comment by kmc059000** [comment]
Also, Cake recommends pinning a project to a specific version of Cake to prevent these errors from happening. https://cakebuild.net/docs/tutorials/pinning-cake-version

**Comment by kmc059000** [comment]
I attempted to upgrade to Cake.Core 0.22.0 in the project, but either I am not setup correctly to .net core development or the Cake.SqlServer will have to be upgraded to .net core. I was unable to upgrade Cake.Core to 0.22.0 using nuget. I received:

Could not install package 'Cake.Core 0.22.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by trailmax** [comment]
easy, guys. Working on this right this moment. New package will be available soon.

**Comment by trailmax** [comment]
Sorry, can't release just now -(((
I run into this issue https://github.com/cake-build/cake/issues/1798 and can't run my build

**Comment by trailmax** [comment]
ghm... hardcoded the version number into the script to avoid running GitVersion and the new package is available to use. Let me know if version numbers cause issues
