### ISSUE TITLE
Add support for v13.0 LocalDB

### ISSUE THREAD

**Issue by KenticoMartinS** [AMVSoftware/Cake.SqlServer#36]
Hi, please would it be possible to add support for v13.0 LocalDB?

Thank you

**Comment by trailmax** [comment]
Sure. Not looked into new version yet. Is it much different from the previous versions? or is this just a matter of a toggle to allow for `-v13`?

Just back from holidays. Will look into that in the next few days.

**Comment by KenticoMartinS** [comment]
To be honest, I don't know if it is different from the previous versions. For me, it would be sufficient if I am able to use Cake.SqlServer on Windows machine that has only LocalDB 13.0 installed.

I hope it is only matter of a toggle to allow `-v13`, but I am not sure.

**Comment by trailmax** [comment]
If you omit the version of LocalDB from your script - the latest installed verion will be used by default. 

Also, can you please check where is your version of LocalDB is installed? I'm currently checking the [following locations](https://github.com/AMVSoftware/Cake.SqlServer/blob/ce098bb93d0b90b6f213af775dade3ad37ae4262/src/Cake.SqlServer/LocalDb/LocalDbToolRunner.cs#L48). I wonder if you have different paths?

**Comment by KenticoMartinS** [comment]
It seems that paths are OK. So the problem will be elsewhere and maybe we are using it incorrectly. 

Our usage:

```
private void InitTestInstance()
{
    // Update connection string to testing DB instance
    const string testsAppConfig = "../Tests/app.config";
    var testConfig = new FilePath(testsAppConfig);
    var connectionString = UpdateConnectionString(testConfig);

    Information($"Connection string to LocalDB is {connectionString}");
    Information("====== Creating instance");
    LocalDbCreateInstance(TestingInstanceName);
    Information("====== Starting instance");
    LocalDbStartInstance(TestingInstanceName);
    Information("====== Creating database");
    CreateDatabaseIfNotExists(connectionString, TestingDatabaseName);
}

private string UpdateConnectionString(Cake.Core.IO.FilePath testConfig) 
{

    var connectionString = GetConnectionStringWithoutDB(TestingInstanceName);
    // Code for setting connection string into app.config

    return connectionString;
}

private string GetConnectionStringWithoutDB(string instanceName)
{
    return $"Data source=(localdb)\\{instanceName}" ;
}
```

And the output is:
```
========================================
Tests
========================================
Connection string to LocalDB is Data source=(localdb)\IntegrationTests 
====== Creating instance
Executing SQLLocalDB.exe with action Create on instance IntegrationTests
An error occurred when executing task 'Tests'.
Looks like you are trying to connect to LocalDb. Have you correctly escaped your connection string with '@'? It should look like 'var connString = @"(localDb)\v12.0"'
Error: One or more errors occurred.                  
```

It seems that the error is in **LocalDbCreateInstance()** method, but we are not passing any connection string into this method.

**Comment by trailmax** [comment]
Some things to try: you don't need `LocalDbStartInstance` right after `LocalDbCreateInstance` - when new instance is created it is automatically started. I don't think this is your problem, but worth a try removing that line.

That exact error appers when your client can't connect to the DB: https://github.com/AMVSoftware/Cake.SqlServer/blob/192f320cf20d0f56915e9d4517ca3874f9dabd7a/src/Cake.SqlServer/SqlServerAliasesImpl.cs#L160 

Can you actually connect to `(localdb)\IntegrationTests ` from SSMS?

**Comment by KenticoMartinS** [comment]
There is no SSMS installed on the machine, only the LocalDB utility. After I used Diagnostic verbosity, it seems that the LocalDB instance wasn't created, but there is no reason why.

```
Executing task: Test
Connection string to LocalDB is Data source=(localdb)\IntegrationTests
====== Creating instance
Executing SQLLocalDB.exe with action Create on instance IntegrationTests
Executing SQLLocalDB.Exe with parameters: create "IntegrationTests" -s

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. The specified LocalDB instance does not exist.
```

**Comment by trailmax** [comment]
Can you run `SQLLocalDB.exe` yourself to verify that it works and the problem is indeed with Cake?

**Comment by KenticoMartinS** [comment]
This is output from `SQLLocalDB.exe`:
```
sqllocaldb.exe info
MSSQLLocalDB

sqllocaldb.exe create "IntegrationTests" -s
LocalDB instance "IntegrationTests" created with version 13.1.4001.0.
LocalDB instance "IntegrationTests" started.

sqllocaldb.exe i "IntegrationTests"
Name:               IntegrationTests
Version:            13.1.4001.0
Shared name:
Owner:              
Auto-create:        No
State:              Running
Last start time:    9/19/2017 3:30:10 PM
Instance pipe name: np:\\.\pipe\LOCALDB#9B9EBB5A\tsql\query

sqllocaldb.exe p "IntegrationTests"
LocalDB instance "IntegrationTests" stopped. 

sqllocaldb.exe d "IntegrationTests"
LocalDB instance "IntegrationTests" deleted.
```

**Comment by trailmax** [comment]
hm.. could that be permissions issue? do you get this error on build server and if you run the script yourself?

**Comment by KenticoMartinS** [comment]
You are right, it was a permission issue on the build server :( Thanks a lot for help

**Comment by trailmax** [comment]
yeah, permissionso on build server are always a pain! 
Glad your problem is sorted!

I'll keep this issue open for myself for actually adding V13 toggle to specify this version of LocalDB

**Comment by trailmax** [comment]
Support for v13 will be available in next version of Cake.SqlServer
