### ISSUE TITLE
No option to supply SQL CMD variables

### ISSUE THREAD

**Issue by roberino** [AMVSoftware/Cake.SqlServer#38]
The SqlCommandVariableValues property on DacDeployOptions doesn't seem to be exposed and so I can't find a way to supply SQL CMD variables in my Cake script.

Is this something planned for a future release or have I missed something in the docs?

**Comment by trailmax** [comment]
@roberino no, you are not missing anything. And no, there was no plans on implementing this, as I was not aware of the property. DAC deployment was implemented by somebody else via a pull request, so I did not know if that was an option. 

I'll have a look on that when I have a moment - if this is just a property on the params object, then it should be easy enough to implement.

**Comment by trailmax** [comment]
@roberino Added this parameter via https://github.com/AMVSoftware/Cake.SqlServer/commit/bac5f787eb1e0c6f33f747bc2722c8897a071132 
It will be available on NuGet after the new package is getting indexed - should be within 20 minutes.
