### ISSUE TITLE
Support for SQL 2017

### ISSUE THREAD

**Issue by LittleColin** [AMVSoftware/Cake.SqlServer#43]
It would be great if you could move to 140.* version of Microsoft.SqlServer.DacFx.x64 so that dacpacs can be deployed to SQL 2017.

https://www.nuget.org/packages/Microsoft.SqlServer.DacFx.x64/

**Comment by trailmax** [comment]
Last time I looked on 140.* version, it caused a lot of trouble and did not work as expected, a lot of tests have failed. 
But I see there is a fresh version of 2 months old, I'll give it another go. It might also fix issue #18 🤞

**Comment by trailmax** [comment]
unfortunately new version of the package still contain the same issues as other from 140.* branch: https://ci.appveyor.com/project/trailmax/cake-sqlserver/build/1.8.5-DacFXUpdate.1+8.build.192#L662

**Comment by trailmax** [comment]
Not a year have passed...
Sql Server 2017 and Azure SQL should be supported in v2.0.1 - DacFX was updated with the promise to get these features available.
