### ISSUE TITLE
Upgrade for Cake 0.26

### ISSUE THREAD

**Issue by jnm2** [AMVSoftware/Cake.SqlServer#44]
Back to these good ol' days:

> The assembly 'Cake.SqlServer, Version=1.8.4.0, Culture=neutral, PublicKeyToken=null'
> is referencing an older version of Cake.Core (0.22.2).
> This assembly need to reference at least Cake.Core version 0.26.0.
> Another option is to downgrade Cake to an earlier version.
> It's not recommended, but you can explicitly opt-out of assembly verification
> by configuring the Skip Verification setting to true
> (i.e. command line parameter "--settings_skipverification=true",
> environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
> read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by trailmax** [comment]
Yep. 
Was planning to update and make a new release tonight along with a few other issues fixed

**Comment by jnm2** [comment]
Okay. I'm happy pinning 0.25 for the time being, so no rush.

**Comment by trailmax** [comment]
Updated in 58f96c46e07d59c64d025fcafec3adf83e931ad6
