### ISSUE TITLE
Readme 'gotcha' section is incorrect

### ISSUE THREAD

**Issue by jnm2** [AMVSoftware/Cake.SqlServer#5]
https://github.com/AMVSoftware/Cake.SqlServer#gotchas:

> If you are in VisualStudio, it'll tell you that the "escape sequence is not valid", but Cake won't tell you that - it'll just transform your string into something you don't expect.

This is actually not true as far as I can tell. `"(localDb)\v12.0"` does not cause Visual Studio to tell you that the escape sequence is invalid because it is valid. `\v` is vertical tab. There is actually no difference between Visual Studio and Cake as far as I know.

Maybe the sentence could read:

> `\v` is the C# escape sequence for vertical tab which is not what you want. Using the verbatim string syntax `@` prevents escape sequences from being interpreted and you get what you expect, verbatim `\` and `v` characters.

**Comment by trailmax** [comment]
Good shout. I'll get this fixed.

**Comment by trailmax** [comment]
Fixed by 9042173
