### ISSUE TITLE
Request for CreateDatabase

### ISSUE THREAD

**Issue by jnm2** [AMVSoftware/Cake.SqlServer#6]
You provide `CreateDatabaseIfNotExists` but in my case it should be an error if the database exists. `CreateDatabase` would suit my purposes perfectly, and it's shorter and more to the point of what I'm doing.

In the [`DropAndCreateDatabase`](https://github.com/AMVSoftware/Cake.SqlServer#drop-and-create-database) reference you state it's a shorthand for `DropDatabase` and `CreateDatabase`. I was expecting to be able to use `CreateDatabase` when I saw this.

**Comment by trailmax** [comment]
That is another good suggestion - thank you! First I had just `CreateDatabase`, but before anything got published renamed it.

I'll get this added.

**Comment by trailmax** [comment]
Added this option release v1.2.0
