### ISSUE TITLE
Question: SQLServer versions support

### ISSUE THREAD

**Issue by RosenPetrov** [AMVSoftware/Cake.SqlServer#63]
Hello,
I am planning to use Cake.SqlServer 2.2.0 version. What MSSQL Server versions does it support? I need it for Backup/Restore databases on MSSQL Server 2017 and 2014.  
Kind regards

**Comment by trailmax** [comment]
Backup/restore are done via generated SQL and it was tested against SQL Server 2019. So it should work with 2014/2017 as well.
