### ISSUE TITLE
Request for RestoreDatabase

### ISSUE THREAD

**Issue by jnm2** [AMVSoftware/Cake.SqlServer#7]
It could be nice to provide a `RestoreDatabase(string connectionString, string databaseName, FilePath backupFile)` to `quotename` escape the string and the name to do this:

```c#
ExecuteSqlCommand(connectionString, "restore database [" + escapedDatabaseName + "] from disk = N'" + escapedBackupFileFullPath + "'");
```

When creating a code sample, the connection string should not specify the database name (similar to CreateDatabase) because it's recommended that the master database be used for restore operations.

**Comment by jnm2** [comment]
Here's what I'm currently doing. You don't have to do anything with any of this but I thought it might prompt ideas:

Because I can't use extension methods in .cake, I'm using https://gist.github.com/jnm2/b00ef6455b532e3893b7220ccf6f4ba6

Then:
```c#
void RestoreDatabase(string connectionString, string databaseName, string backupFile, IReadOnlyDictionary<string, FilePath> moveLocationsByName = null)
{
    var sql = new SqlStringBuilder().AppendRaw("restore database ").AppendSqlName(databaseName).AppendRaw(" from disk = ").AppendSqlLiteral(backupFile);

    if (moveLocationsByName != null)
    {
        sql.AppendRaw(" with");
        var isFirst = true;
        foreach (var locationByName in moveLocationsByName)
        {
            if (isFirst) isFirst = false; else sql.AppendRaw(',');
            sql.AppendLine()
                .AppendRaw("   move ").AppendSqlLiteral(locationByName.Key)
                .AppendRaw(" to ").AppendSqlLiteral(MakeAbsolute(locationByName.Value).FullPath.Replace('/', '\\'));
        }
    }

    ExecuteSqlCommand(connectionString, sql.ToString());
}
```

Then:
```c#
IDisposable TempDatabaseFromBackup(string connectionString, string databaseName, string backupFile, IReadOnlyDictionary<string, FilePath> moveLocationsByName = null)
{
    RestoreDatabase(connectionString, databaseName, backupFile, moveLocationsByName);
    return On.Dispose(() => DropDatabase(connectionString, databaseName));
}
```

And I use it like so:
```c#
var databaseName = "ProjectName integration " + Guid.NewGuid();

using (TempDatabaseFromBackup(
    new SqlConnectionStringBuilder { DataSource = @"(LocalDb)\MSSQLLocalDB" }.ToString(),
    databaseName,
    @"path/to/backup.bak",
    new Dictionary<string, FilePath>
    {
        { "DatabaseName", "temp/DatabaseName.mdf" },
        { "DatabaseName_log", "temp/DatabaseName_log.ldf" }
    }))
{
    var connectionString = new SqlConnectionStringBuilder { DataSource = @"(LocalDb)\MSSQLLocalDB", InitialCatalog = databaseName }.ToString();
    // ...
}
```

**Comment by trailmax** [comment]
###Note for implementation

* Use `RESTORE FILELISTONLY from Disk = 'd:\backup.bak' ` to get list of logical names - these are needed if `Move` is used. Read it in C# because results can't be easily stored in SQL
* Instead of dictionary with LogicalNames/path, take only folder where new mdf/ldf will be stored. Take logical names from the previous step, generate full path based on base path and new db-name

**Comment by trailmax** [comment]
@jnm2 Can you please take a look at https://github.com/AMVSoftware/Cake.SqlServer/blob/RestoreDatabase/src/Cake.SqlServer/SqlServerAliasesImpl.cs#L173

With usage being like this https://github.com/AMVSoftware/Cake.SqlServer/blob/RestoreDatabase/src/Tests/RestoreDatabaseTests.cs#L33

Does it look useful?

**Comment by jnm2** [comment]
It's useful for me for the immediate future, but what if someone has a database with .ndf files or multiple .ldfs? The only reason I used a dictionary was to make myself responsible to know that information rather than relying on a convention.

This isn't for Cake, but the generic TSQL I use for day-to-day restores: `restore headeronly` to get the original database name, `restore filelistonly` to figure out what files I need to come up with names for, and then replace all instances of the original database name in the filenames with the new name.

**Comment by trailmax** [comment]
@jnm2  My plan was to do `*.mdf` restore a separate function along with restores from `*.bacpac`.  Why do you need to run `restore headeronly` separately? does `restore filelistonly` not contain the database name? I mean can logical name for mdf file be different from the original database name?

**Comment by jnm2** [comment]
I just think it's safer to read the actual database name rather than relying on the convention that master data file's logical name will match. It looks like the logical file name can be changed, too, without affecting the database name.

https://dba.stackexchange.com/questions/66173/sql-server-filelistonly-command-providing-incorrect-logical-database-name

**Comment by trailmax** [comment]
backup restore is now implemented in v1.5.0.
@jnm2  thanks for the link to the SQL script - that was the good inspiration to complete this issue.

**Comment by jnm2** [comment]
These days what I'm doing has diverged significantly:

```c#
RestoreDatabase(connection, backupSourcePath, databaseName);
// For use later on
var originalDbName = GetSqlBackupDatabaseNames(connection, backupSourcePath).Single();
```

https://gist.github.com/jnm2/b6e9c51ed9c7ec5ecfbb9fa7def02d4b

**Comment by trailmax** [comment]
@jnm2 is this a better approach? what is the difference from what is available in the current codebase?

**Comment by jnm2** [comment]
@trailmax Oh maybe, not necessarily. I just tried to replace what I was doing with your RestoreDatabase alias and didn't see a way to do that, so posted when I am doing in case you found an interesting element in it. I don't know if that's a scenario you want to cover.

**Comment by trailmax** [comment]
I'm keen to cover all the valid scenarios, yet I'm not entirely sure what happens in your snippet. Do you replace the DB names when you restore them?

**Comment by jnm2** [comment]
My RestoreDatabase is doing the C# equivalent of the [SQL script I posted](https://gist.github.com/jnm2/d5f721c06f67b2f07eacbe33044ad03c) awhile back:

 1. Get the single database name from the backup. (I don't have backups with multiple databases but if I did, the target database name would have to be passed in.) This is the original database name.
 2. Get the instance's default data and log paths.
 3. For each file, replace the original database name with the new database name (if they are different) and combine with the instance's default data and log paths.

**Comment by jnm2** [comment]
But you could also pass in your own `Func<FileDestinationCalculatorArgs, FilePath>` to customize your own paths given `e.LogicalName`, `e.PhysicalName`, and `e.Type`.

**Comment by trailmax** [comment]
I see. I have all that hidden and without an option to tap in - internal funcs. I think it'll be relatively easy to add stuff you need without breaking existing functionality. I'll see what can be done, probably over the weekend

**Comment by jnm2** [comment]
It's up to you what you think is worth adding. I'm frankly not even using the `fileDestinationCalculator` parameter.
